package modelo;

public enum Evento {
	CAMBIO_LISTA_DE_JUGADORES,
	JUGADOR_AGREGADO,
	JUGADOR_ELIMINADO,
	JUGADOR_YA_EXISTE,
	FALTAN_JUGADORES,
	MAXIMO_DE_JUGADORES,
	LISTO_PARA_INICIAR,
	JUEGO_INICIADO,
	CAMBIO_TURNO,
	CAMBIO_DADOS,
	FINALIZO
}
