package modelo;

public enum Evento {
	CAMBIO_LISTA_DE_JUGADORES,
	JUGADOR_AGREGADO,
	JUGADOR_ELIMINADO,
	JUGADOR_YA_EXISTE,
	FALTAN_JUGADORES,
	MAXIMO_DE_JUGADORES,
	LISTO_PARA_INICIAR,
	JUEGO_INICIADO,
	POKER_REAL,
	POKER_CUADRUPLE,
	FULL,
	ESCALERA_MAYOR,
	ESCALERA_MENOR,
	PIERNA,
	PARES_DOBLES,
	PARES,
	NO_HAY_JUEGO,
	CAMBIO_TURNO,
	CAMBIO_DADOS,
	JUEGO_FINALIZADO
}
